### ISSUE TITLE
ipv6 DNS server breaks ui container

### ISSUE THREAD

**Issue by tillnelown** [tess1o/geopulse#111]
I have an uplink ipv6 DNS server set in /etc/resolv.conf on the host, it seems that the ui container tries to take both of my DNS Servers and use them but doesn't format the ipv6 for nginx creating the following Error:

```
geopulse-ui[3274230]: Updated nginx configuration:
geopulse-ui[3274230]:   - backend: http://geopulse-backend:8080
geopulse-ui[3274230]:   - client max body size: 1000M
geopulse-ui[3274230]:   - OSM resolver: fd4d:27db:d17f:b30d:b0cc:bfff:fe97:764f 100.64.5.1
geopulse-ui[3274230]: 2025/11/02 01:07:38 [emerg] 1#1: invalid port in resolver "fd4d:27db:d17f:b30d:b0cc:bfff:fe97:764f" in /etc/nginx/conf.d/default.conf:23
geopulse-ui[3274230]: nginx: [emerg] invalid port in resolver "fd4d:27db:d17f:b30d:b0cc:bfff:fe97:764f" in /etc/nginx/conf.d/default.conf:23
```
content of hosts /etc/resolv.conf:
```
nameserver fd4d:27db:d17f:b30d:b0cc:bfff:fe97:764f
nameserver 100.64.5.1
```

**Comment by tess1o** [comment]
I will check that. As a workaround set OSM_RESOLVER via env variable to correct dns server

**Comment by tess1o** [comment]
Fixed. New release will be delivered today

**Comment by tess1o** [comment]
The fix is implemented in release `1.2.0`. See changelog here: https://github.com/tess1o/geopulse/releases/tag/1.2.0

**Comment by tillnelown** [comment]
While i can see the fix 6659acde860153d6522cbc806d95af23743c3494, the ghcr image doesn't seem to have it. I've pulled the latest image on two machines but in both I can still see the file as it was before the commit.

`$:podman run --pull=always --entrypoint sh -it --rm ghcr.io/tess1o/geopulse-ui:1.2.0`
`$ cat /docker-entrypoint.sh`
```
...
SYSTEM_NAMESERVERS=$(grep '^nameserver' /etc/resolv.conf | awk '{print $2}' | paste -sd " " -)
...
```

**Comment by tess1o** [comment]
That's strange.. I will check and let you know. Sorry for inconvenience.

**Comment by tess1o** [comment]
@tillnelown please pull new image (the same tag) and let me know if it works for you.

Thanks.

**Comment by tillnelown** [comment]
New image does contain the changes and fixes this issue. Thanks 👍
