### ISSUE TITLE
What is the logic behind Geopulse's walking calculation? It shows that I walked 10.57 km in 28 minutes.

### ISSUE THREAD

**Issue by goxofy** [tess1o/geopulse#119]
<img width="321" height="184" alt="Image" src="https://github.com/user-attachments/assets/51ce63ae-6521-4d96-aeb6-c481a365d477" />

**Comment by tess1o** [comment]
Please export data for debug using this url: /app/debug-export  (available in release `1.2.0`)
The coordinates will be shifted to a random value so I won't get your exact coordinates but I will be able to investigate this.

we try to calculate it based GPS data but due to different reasons it might fail to properly calculate the trip type. So your data is needed to identify exactly what happened. 

Thanks.

**Comment by goxofy** [comment]
Thanks a lot, I have exported the GPS data and time configurations, should I upload zip file in this ISSUE?

**Comment by tess1o** [comment]
Either here or upload it somewhere. All your coordinates were shifted to a random value unknown to us, so that zip file doesn't contain your personal data

**Comment by goxofy** [comment]
@tess1o ok thanks！

**Comment by tess1o** [comment]
@goxofy ,
What app do you use to import your data? I see speed is not available in your data (you can verify the same on GPS Data), thus the algorithm failed to understand that it was a car trip. I can do some improvements to estimate if such trip is possible (10.5 KM in 28 minutes is not possible for a walk) and override algorithm's decision but looks like the main issue in your case that the velocity (speed) is not available at all.

Thanks.

**Comment by goxofy** [comment]
Thanks！

I import GPS data from Home assistant，and my HA device_track entity doesn't have speed data indeed. 

Maybe the average speed can be calculated by dividing distance by time?

**Comment by tess1o** [comment]
Yes, I will do similar approach as a "last chance" to guess the movement type.

**Comment by goxofy** [comment]
OK Thanks!

**Comment by tess1o** [comment]
I made improvements here and the fix is available in release 1.2.1. Full changelog is here: https://github.com/tess1o/geopulse/releases/tag/1.2.1

You might want to Regenerate your timeline (Go to Preferences, click on Regenerate Timeline)

**Comment by goxofy** [comment]
Hi @tess1o , I have updated to 1.2.1, but it seems like still shows  Movement: 🚶‍♂️ Walk

Thanks

**Comment by tess1o** [comment]
Please regenerate timeline (Preferences - Regenerate timeline). Existing data won't be fixed automatically

**Comment by goxofy** [comment]
Hi @tess1o , I have regenerate timeline (Preferences - Regenerate timeline), the existing data regenerate new timeline still shows Movement: 🚶‍♂️ Walk.

Maybe only new data then will shows car or other?

**Comment by tess1o** [comment]
No, it should show CAR even now. That's strange, worked for me in unit tests with about the same data you have. Is it one occurrences of wrong type or you have multiple examples? If many examples are there - please export data like you did previously but take bigger period of time.

Generally speaking this case (no speed available) is an edge case - to properly build timeline you still need to know speed - stops (stays, visits) are also dependent on speed change and it's value. I will try to look to overall algorithm further to find if there are other places where we do wrong calculations (not about movement type but for timeline in general) without speed available.

Thanks.

**Comment by goxofy** [comment]
@tess1o Hi, it is only one trip example (above exported data) at this time, that is the same timeline I regenerate.

Thanks a lot.

Waiting for your update.

**Comment by FoxxMD** [comment]
I don't have specific time ranges/data to show for this but I'm _quite_ sure my walking total is very off. 

<img width="351" height="346" alt="Image" src="https://github.com/user-attachments/assets/73354c80-d3b1-49bf-b8c4-cb726105011c" />

All my data imports have been from google timeline and then from Home Assistant data, exported from Dawarich. I'm not sure if it had speed. I imagine a large part of that walking distance is time in an airplane.

**Comment by tess1o** [comment]
@FoxxMD 

Please export example via "/app/debug-export" (add +- few days to be sure I have enough data to build timeline) where you had flight or where you for 100% have wrong movement type. I will check that example to figure out what's wrong.

I don't have much real examples with flights or just regular GPS data (stays, trips, walking,cars, etc) without speeds (probably I can take my own data and delete speed) so it's quite hard to cover such cases.

Appreciate your feedback.

**Comment by tess1o** [comment]
Closing this issue due to inactivity. Feel free to create a new one - attach debug data from "/app/debug-export" page and explain your issue.

**Comment by FoxxMD** [comment]
Hey sorry I haven't followed up on this. I will get a proper report in here eventually. In the meantime, stats seem to have gotten more accurate. On 1.4.2 my walking distance is more reasonble, but I think maybe the distance just shifted to car 😅 

<img width="1186" height="370" alt="Image" src="https://github.com/user-attachments/assets/e4dd4b27-4577-482c-b900-6986e7f46321" />
