### ISSUE TITLE
immich connection not reporting correctly

### ISSUE THREAD

**Issue by xamindar** [tess1o/geopulse#216]
I'm trying to get immich working, but maybe that feature is not built yet? 
It doesn't seem to matter what I put in for the url, whether a wrong value, or the correct value, it always says it is connected. This is on the Profile->immich--enter in url and api key. Is it even checking connectivity, or blindy reporting "connected" instead?

For example:
Connected
Connected to: http://immich-server:2283

In either case, I can't get it to work, and do not see anything in the container logs that would point me towards the problem.

**Comment by tess1o** [comment]
You're right, that "Connected to" was showing wrong information. I've fixed it and will deliver the fix tomorrow.

After the fix:

<img width="534" height="769" alt="Image" src="https://github.com/user-attachments/assets/6ae8f504-4d43-4623-b046-3d724ee96f0c" />

These permissions is enough:

<img width="978" height="153" alt="Image" src="https://github.com/user-attachments/assets/bc725fb0-4dbd-446b-9345-d13228234a15" />

Once configured on the timeline map you will see additional icon (at the bottom)

<img width="46" height="163" alt="Image" src="https://github.com/user-attachments/assets/188aaa39-8883-4e90-88c9-7394c9e5aab8" />

When enabled it will show photos from Immich server for the corresponding timeframe. Obviously the photos should have coordinates information so we can display them on the map.

It will look like this:

<img width="99" height="142" alt="Image" src="https://github.com/user-attachments/assets/88b1b0d2-51a8-412c-8b49-685f3966e78a" />

Number 2 here means there are 2 photos on the same location.

**Comment by tess1o** [comment]
Fixed in 1.7.0

**Comment by xamindar** [comment]
Thank you, it now reports a successful connection when I use the test connection button. 

I still do not see any photos on my map, ever. I know a lot were taken at my home spot but for whatever reason it doesn't seem to work.

**Comment by tess1o** [comment]
Check if you see location for your photos in Immich itself. We use metadata from Immich to find coordinates for each photo. If you don't see location for photos in immich then we can't properly it display such photos on the map. If you see location in immich - I will provide additional steps for debugging.

**Comment by xamindar** [comment]
OMG you are totally right! I had location saving turned off on my phone. Turned it on and took some pictures and now see a "3" on the map. Sorry for wasting your time.

**Comment by tess1o** [comment]
No worries. I'm glad we sorted this out

**Comment by CrazyWolf13** [comment]
Thank you, the permissions was really helpful, maybe this would be worth a note in the docs?

**Comment by tess1o** [comment]
@CrazyWolf13 the documentation was updated: https://tess1o.github.io/geopulse/docs/user-guide/personalization/immich-integration

<img width="862" height="64" alt="Image" src="https://github.com/user-attachments/assets/2b9c5fe1-600a-4669-8a48-a4adb9942283" />
