### ISSUE TITLE
Google Timeline import fails to upload due to size, underneath documented maximum

### ISSUE THREAD

**Issue by FoxxMD** [tess1o/geopulse#4]
Trying to import Google Timeline JSON (`Timeline.json`) file that is 75MB, less than the 100MB max shown on the import page, results in an error in the UI:

```
Import Failed
Request failed with status code 413
```

and geopulse-ui service logs this:

```
2025/10/22 17:24:41 [error] 12#12: *115 client intended to send too large body: 75347190 bytes, client: 10.0.2.57, server: localhost, request: "POST /api/import/google-timeline/upload HTTP/1.1", host: "REMOVED", referrer: "https://REMOVED/app/data-export-import"
```

**Comment by tess1o** [comment]
Thanks for reporting. Mine was 1MB only :) I will check this out.

**Comment by FoxxMD** [comment]
@tess1o its also occurring on GPX import, if that matters. Failed to upload 16MB `.gpx` file with the same error.

**Comment by tess1o** [comment]
It's the default nginx configuration that needs to be updated. I'll do today.

**Comment by tess1o** [comment]
I've added `client_max_body_size 200M;`  so it should work now.  I pushed new image for frontend to dockerhub (the same tag name for now), so please pull new image for frontend and recreate frontend container (make sure new image is pulled and container is created with new image). If everything is OK - I will push the fix to version 1.0.1

Image ID:
`tess1o/geopulse-ui:1.0.0@sha256:03ed65a7266303d14fbc18409fa8a6b0456facac22cbc58242f5e0c82f87952c`

P.S. Since you try to upload pretty big files I'd suggest to update "mem_limit" in your docker compose (for backend part). Current value 512Mb might be low for such big files.

Thank you.

**Comment by FoxxMD** [comment]
I'm able to successfully upload files but both my imports are failing for other reasons, now.

For gpx (from dawarich)

```
geopulse-backend  | 2025-10-22 19:38:30,476 INFO  [org.git.tes.geo.imp.res.ImportResource] (executor-thread-4) Received GPX import request for user: 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-22 19:38:30,484 INFO  [org.git.tes.geo.imp.ser.ImportService] (executor-thread-4) Created GPX import job efd2723f-15e4-4f61-8baf-179becf2e8bc for user 91da95af-3517-46c1-a711-5a11a1ebcf92 with file: export_from_2025-01-01_to_2025-10-22.gpx
geopulse-backend  | 2025-10-22 19:38:30,999 INFO  [org.git.tes.geo.imp.ser.ImportDataService] (quarkus-virtual-thread-26) Validating import data for format: gpx and user: 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-22 19:38:31,001 INFO  [org.git.tes.geo.imp.ser.BaseGpsImportStrategy] (quarkus-virtual-thread-26) Validating gpx data for user 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-22 19:38:31,011 ERROR [org.git.tes.geo.imp.ser.ImportService] (quarkus-virtual-thread-26) Failed to validate import job efd2723f-15e4-4f61-8baf-179becf2e8bc: Invalid gpx format: Unrecognized field "schemaLocation" (class org.github.tess1o.geopulse.gps.integrations.gpx.model.GpxFile), not marked as ignorable (7 known properties: "validWaypoints", "version", "wpt", "creator", "allTrackPoints", "metadata", "trk"])
geopulse-backend  |  at [Source: (StringReader); line: 2, column: 276] (through reference chain: org.github.tess1o.geopulse.gps.integrations.gpx.model.GpxFile["schemaLocation"]): java.lang.IllegalArgumentException: Invalid gpx format: Unrecognized field "schemaLocation" (class org.github.tess1o.geopulse.gps.integrations.gpx.model.GpxFile), not marked as ignorable (7 known properties: "validWaypoints", "version", "wpt", "creator", "allTrackPoints", "metadata", "trk"])
geopulse-backend  |  at [Source: (StringReader); line: 2, column: 276] (through reference chain: org.github.tess1o.geopulse.gps.integrations.gpx.model.GpxFile["schemaLocation"])
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.BaseGpsImportStrategy.validateAndDetectDataTypes(BaseGpsImportStrategy.java:65)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.GpxImportStrategy_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService.validateAndDetectDataTypes(ImportDataService.java:30)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processAvailableJobs(ImportService.java:217)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processImportJobs(ImportService.java:199)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ClientProxy.processImportJobs(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ScheduledInvoker_processImportJobs_0f300e332ad99ca81116475ae6c2150ed42afafe.invokeBean(Unknown Source)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:25)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeComplete(DelegateInvoker.java:36)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.OffloadingInvoker$1$1.run(OffloadingInvoker.java:45)
geopulse-backend  | 	at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
geopulse-backend  | 	at java.base@25/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
geopulse-backend  | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend  | 	at java.base@25/java.lang.VirtualThread.run(VirtualThread.java:456)
geopulse-backend  | 	at java.base@25/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:248)
geopulse-backend  | 
```

For google timeline

```
geopulse-backend  | 2025-10-22 19:39:18,890 INFO  [org.git.tes.geo.imp.res.ImportResource] (executor-thread-5) Received Google Timeline import request for user: 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-22 19:39:18,924 INFO  [org.git.tes.geo.imp.ser.ImportService] (executor-thread-5) Created Google Timeline import job 698e25ab-19a7-4284-adc7-4a624f580832 for user 91da95af-3517-46c1-a711-5a11a1ebcf92 with file: Timeline.json
geopulse-backend  | 2025-10-22 19:39:18,999 INFO  [org.git.tes.geo.imp.ser.ImportDataService] (quarkus-virtual-thread-50) Validating import data for format: google-timeline and user: 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-22 19:39:18,999 INFO  [org.git.tes.geo.imp.ser.BaseGpsImportStrategy] (quarkus-virtual-thread-50) Validating google-timeline data for user 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-22 19:39:19,099 ERROR [org.git.tes.geo.imp.ser.ImportService] (quarkus-virtual-thread-50) Failed to validate import job 698e25ab-19a7-4284-adc7-4a624f580832: Invalid google-timeline format: Cannot deserialize value of type `java.util.ArrayList` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]: java.lang.IllegalArgumentException: Invalid google-timeline format: Cannot deserialize value of type `java.util.ArrayList` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.BaseGpsImportStrategy.validateAndDetectDataTypes(BaseGpsImportStrategy.java:65)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.GoogleTimelineImportStrategy_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService.validateAndDetectDataTypes(ImportDataService.java:30)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processAvailableJobs(ImportService.java:217)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processImportJobs(ImportService.java:199)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ClientProxy.processImportJobs(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ScheduledInvoker_processImportJobs_0f300e332ad99ca81116475ae6c2150ed42afafe.invokeBean(Unknown Source)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:25)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeComplete(DelegateInvoker.java:36)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.OffloadingInvoker$1$1.run(OffloadingInvoker.java:45)
geopulse-backend  | 	at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
geopulse-backend  | 	at java.base@25/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
geopulse-backend  | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend  | 	at java.base@25/java.lang.VirtualThread.run(VirtualThread.java:456)
geopulse-backend  | 	at java.base@25/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:248)
```

I can make separate issues for this if you'd prefer

**Comment by tess1o** [comment]
I know what to do with GPX - will be fixed in next release. In my GPX files I didn't have such fields. Regarding Google Timeline - I'd need to see the structure of your file (obviously you can't share the file itself). How did you get the file? I got mine via Google Takeout.

**Comment by tess1o** [comment]
For google timeline can you please generate json schema from your json file and provide it? The json schema doesn't contain any personal data, just the structure of your file. It can be done via various online services. This should help with the fix.

**Comment by FoxxMD** [comment]
Here's a sample of data from `Timeline.json`, I scrolled through a decent bit and didn't see any other variations as far as data structure goes. I'm sure the semanticType has other enums. I replaced all lat/long with 160xxx for anonymity. 

```
{
  "semanticSegments": [
    {
      "startTime": "2015-09-20T12:00:00.000-04:00",
      "endTime": "2015-09-20T14:00:00.000-04:00",
      "timelinePath": [
        {
          "point": "160.11115°, -160.1111°",
          "time": "2015-09-20T12:15:00.000-04:00"
        },
        {
          "point": "160.11113°, -160.11111°",
          "time": "2015-09-20T12:19:00.000-04:00"
        },
        {
          "point": "160.1111°, -160.11111°",
          "time": "2015-09-20T12:29:00.000-04:00"
        }
      ]
    },
    {
      "startTime": "2015-09-20T12:14:46.000-04:00",
      "endTime": "2015-09-20T12:18:37.000-04:00",
      "startTimeTimezoneUtcOffsetMinutes": -240,
      "endTimeTimezoneUtcOffsetMinutes": -240,
      "activity": {
        "start": {
          "latLng": "160.11115°, -160.1111°"
        },
        "end": {
          "latLng": "160.1111°, -160.1111°"
        },
        "distanceMeters": 212.17379760742188,
        "topCandidate": {
          "type": "WALKING",
          "probability": 0.0
        }
      }
    },
    {
      "startTime": "2015-09-20T12:18:37.000-04:00",
      "endTime": "2015-09-20T12:29:17.000-04:00",
      "startTimeTimezoneUtcOffsetMinutes": -240,
      "endTimeTimezoneUtcOffsetMinutes": -240,
      "visit": {
        "hierarchyLevel": 0,
        "probability": 0.6899999976158142,
        "topCandidate": {
          "placeId": "ndhtSYdhtSYndhtSYaovndhtSYs",
          "semanticType": "UNKNOWN",
          "probability": 0.15664449334144592,
          "placeLocation": {
            "latLng": "160.1111°, -160.1111°"
          }
        }
      }
    }
  ]
}
```

Fairly certain I got this from a takeout. It was after google switched off location/timeline for maps though, irc, so it might have been a different method. It was importable into dawarich..I guess through Semantic Location History which is not the same as Takeout?

EDIT: ah yeah its [not the same](https://dawarich.app/docs/tutorials/import-existing-data/#google-maps-app-export) as takeout. Unfortunately its the only way my past location data is exported, now, since takeout no longer stores timeline data there.

**Comment by tess1o** [comment]
GPX issue is fixed - I will deliver version 1.0.1 later. 

Regarding Google Timeline - is you file the same like this example:
https://github.com/Freika/dawarich/blob/493db274f5f7ed7160e3b65ae58ae3cc941605ca/spec/fixtures/files/google/phone-takeout_w_3_duplicates.json

From the sample you showed looks like yes.

Google Takeout I could do generated file like this: 
https://github.com/Freika/dawarich/blob/493db274f5f7ed7160e3b65ae58ae3cc941605ca/spec/fixtures/files/google/location-history.json

That's why it fails for you now. 

Thanks.

**Comment by cchrkk** [comment]
> Thanks for reporting. Mine was 1MB only :) I will check this out.

Uhm, my timeline file is like a huge 1,5GB json file🥲 Any tip?

**Comment by tess1o** [comment]
Probably increase max file size in nginx (currently 200mb), increase mem_limit for backend container (currently 512Mb,  you would propably need about 10GB RAM with current approach). Currently whole JSON is loaded to memory but with such huge files (1.5 GB) we definitely need to do streaming reading.

**Comment by tess1o** [comment]
@FoxxMD ,
max file size (during upload), GPX import is fixed in version 1.0.1. Google Timeline issue is not fixed yet, waiting for your feedback about file format. Once I confirm the file format I will try to do implementation.
To upgrade to new version update `.env` (variable GEOPULSE_VERSION) and redeploy the app.

**Comment by FoxxMD** [comment]
> https://github.com/Freika/dawarich/blob/493db274f5f7ed7160e3b65ae58ae3cc941605ca/spec/fixtures/files/google/phone-takeout_w_3_duplicates.json

yes this looks like my file. I'll be able to try gpx file tomorrow

**Comment by tess1o** [comment]
Ok, thanks. But as you can see the data from Google doesn't contain speed and pretty limited set of GPS points. So the accuracy of timeline generation will be low.  if you have GPX data or OwnTracks data it's much more preferable format since it contain more GPS data + your speed at different points.

**Comment by FoxxMD** [comment]
GPX data import worked.

>  if you have GPX data or OwnTracks data it's much more preferable format

I didn't start recording this kind of data until dawarich! the timeline data is the only historical data I have pre 2025. I think you'll find most new users coming to dawarich/geopulse don't have rich historical data either, google takeout is going to be a primary source.

**Comment by roopeshvs** [comment]
> Regarding Google Timeline - is you file the same like this example: https://github.com/Freika/dawarich/blob/493db274f5f7ed7160e3b65ae58ae3cc941605ca/spec/fixtures/files/google/phone-takeout_w_3_duplicates.json
> 
> From the sample you showed looks like yes.

I tried to import the timeline I exported from my Android through `Device Settings > Location > Location Services > Timeline > Export  Timeline data`. Can confirm this is the structure I got.

Ran into the following error importing `Timeline.json`

```
geopulse-backend    | 2025-10-23 14:34:16,025 ERROR [org.git.tes.geo.imp.ser.ImportService] (quarkus-virtual-thread-4002) Failed to validate import job 659c7c7f-4ad1-4219-a8e8-13422ac8f553: Invalid google-timeline format: Cannot deserialize value of type `java.util.ArrayList<org.github.tess1o.geopulse.gps.integrations.googletimeline.model.GoogleTimelineRecord>` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend    |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]: java.lang.IllegalArgumentException: Invalid google-timeline format: Cannot deserialize value of type `java.util.ArrayList<org.github.tess1o.geopulse.gps.integrations.googletimeline.model.GoogleTimelineRecord>` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend    |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.BaseGpsImportStrategy.validateAndDetectDataTypes(BaseGpsImportStrategy.java:65)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.GoogleTimelineImportStrategy_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService.validateAndDetectDataTypes(ImportDataService.java:30)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processAvailableJobs(ImportService.java:217)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processImportJobs(ImportService.java:199)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ClientProxy.processImportJobs(Unknown Source)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ScheduledInvoker_processImportJobs_0f300e332ad99ca81116475ae6c2150ed42afafe.invokeBean(Unknown Source)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:25)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeComplete(DelegateInvoker.java:36)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.OffloadingInvoker$1$1.run(OffloadingInvoker.java:45)
geopulse-backend    | 	at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
geopulse-backend    | 	at java.base@25/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
geopulse-backend    | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend    | 	at java.base@25/java.lang.VirtualThread.run(VirtualThread.java:456)
geopulse-backend    | 	at java.base@25/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:248)
```

**Comment by tess1o** [comment]
I didn't have such example when initially implemented this, so as of now such format is not supported. I will try to implement this today-tomorrow. Thank you for patience

**Comment by tess1o** [comment]
Hello,

This issue is fixed in release 1.0.3. In your `.env` file set `GEOPULSE_VERSION=1.0.3` and redeploy the frontend and backend. 
I tested this on a small file and hope it will work you. I don't have better file example...

**Comment by roopeshvs** [comment]
@tess1o Still getting the error in 1.0.3

```
geopulse-backend    | 2025-10-24 15:00:34,197 ERROR [org.git.tes.geo.imp.ser.ImportService] (quarkus-virtual-thread-28) Failed to validate import job 20fab588-c8b8-4981-9801-31cb5661cdef: Invalid google-timeline format: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend    |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 119, column: 18] (through reference chain: org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegmentsRoot["semanticSegments"]->java.util.ArrayList[3]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegment["activity"]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticActivity["start"]): java.lang.IllegalArgumentException: Invalid google-timeline format: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend    |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 119, column: 18] (through reference chain: org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegmentsRoot["semanticSegments"]->java.util.ArrayList[3]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegment["activity"]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticActivity["start"])
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.BaseGpsImportStrategy.validateAndDetectDataTypes(BaseGpsImportStrategy.java:65)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.GoogleTimelineImportStrategy_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService.validateAndDetectDataTypes(ImportDataService.java:30)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processAvailableJobs(ImportService.java:245)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processImportJobs(ImportService.java:227)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ClientProxy.processImportJobs(Unknown Source)
geopulse-backend    | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ScheduledInvoker_processImportJobs_0f300e332ad99ca81116475ae6c2150ed42afafe.invokeBean(Unknown Source)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:25)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeComplete(DelegateInvoker.java:36)
geopulse-backend    | 	at io.quarkus.scheduler.common.runtime.OffloadingInvoker$1$1.run(OffloadingInvoker.java:45)
geopulse-backend    | 	at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
geopulse-backend    | 	at java.base@25/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
geopulse-backend    | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend    | 	at java.base@25/java.lang.VirtualThread.run(VirtualThread.java:456)
geopulse-backend    | 	at java.base@25/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:248)
```

I am attaching the schema I was able to generate and validate: https://gist.github.com/roopeshvs/799b1dbac560aba336b044b9c349c99c
Hope it helps.

**Comment by FoxxMD** [comment]
I am seeing a similar error:

```
geopulse-backend  | 2025-10-24 16:10:05,000 INFO  [org.git.tes.geo.imp.ser.BaseGpsImportStrategy] (quarkus-virtual-thread-515) Validating google-timeline data for user 91da95af-3517-46c1-a711-5a11a1ebcf92
geopulse-backend  | 2025-10-24 16:10:06,135 ERROR [org.git.tes.geo.imp.ser.ImportService] (quarkus-virtual-thread-515) Failed to validate import job 7ffd21ae-dd0d-4784-8118-180f24e2bb42: Invalid google-timeline format: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 27, column: 18] (through reference chain: org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegmentsRoot["semanticSegments"]->java.util.ArrayList[1]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegment["activity"]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticActivity["start"]): java.lang.IllegalArgumentException: Invalid google-timeline format: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
geopulse-backend  |  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 27, column: 18] (through reference chain: org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegmentsRoot["semanticSegments"]->java.util.ArrayList[1]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticSegment["activity"]->org.github.tess1o.geopulse.gps.integrations.googletimeline.model.semanticsegments.GoogleTimelineSemanticActivity["start"])
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.BaseGpsImportStrategy.validateAndDetectDataTypes(BaseGpsImportStrategy.java:65)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.GoogleTimelineImportStrategy_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService.validateAndDetectDataTypes(ImportDataService.java:30)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportDataService_ClientProxy.validateAndDetectDataTypes(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processAvailableJobs(ImportService.java:245)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService.processImportJobs(ImportService.java:227)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ClientProxy.processImportJobs(Unknown Source)
geopulse-backend  | 	at org.github.tess1o.geopulse.importdata.service.ImportService_ScheduledInvoker_processImportJobs_0f300e332ad99ca81116475ae6c2150ed42afafe.invokeBean(Unknown Source)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:25)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeComplete(DelegateInvoker.java:36)
geopulse-backend  | 	at io.quarkus.scheduler.common.runtime.OffloadingInvoker$1$1.run(OffloadingInvoker.java:45)
geopulse-backend  | 	at io.quarkus.virtual.threads.ContextPreservingExecutorService$ContextPreservingRunnable.run(ContextPreservingExecutorService.java:45)
geopulse-backend  | 	at java.base@25/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:291)
geopulse-backend  | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend  | 	at java.base@25/java.lang.VirtualThread.run(VirtualThread.java:456)
geopulse-backend  | 	at java.base@25/java.lang.VirtualThread$VThreadContinuation$1.run(VirtualThread.java:248)
```

**Comment by tess1o** [comment]
Thank you for providing the schema.  The schema and this test file I used as a reference are different:

https://github.com/Freika/dawarich/blob/493db274f5f7ed7160e3b65ae58ae3cc941605ca/spec/fixtures/files/google/phone-takeout_w_3_duplicates.json

That's why it doesn't work for you and fails on parsing part.

@UltimatumGamer created a PR to fix this (thank you very much), so a new fix will be provided soon. I see his fix is almost correct. I will verify it, update unit test and deliver new fix.

**Comment by tess1o** [comment]
The fix (verified with provided json schema) was merged, I will create a new docker image later today.

**Comment by tess1o** [comment]
@FoxxMD , @roopeshvs 

Fixed in `1.0.5` - please try this version and let me know if it finally works.

Thanks!

**Comment by tess1o** [comment]
In version `1.1.0` I completely re-implemented Google Timeline import. Now we use streaming approach and we don't even store whole file in memory. Thus, the memory usage is about +40-50 MB on beginning and then when drops dramatically. It was a 500MB file I generated for tests.

The import is started right after container start so initial memory usage is till high - unused memory was not released back to OS. At this moment parsing in streaming mode and inserts to DB (500 points per batch) was still in progress.

<img width="1494" height="700" alt="Image" src="https://github.com/user-attachments/assets/4888c66a-c43a-42be-bc65-531e4d06a76a" />

 I will publish this version soon, probably on Oct 27th.

**Comment by FoxxMD** [comment]
I will be able to test this out tomorrow (or whenever you publish it, tomorrow or afterwards)

**Comment by tess1o** [comment]
Hello,

This issue is fixed in version 1.1.0. Full changelog is available here: https://github.com/tess1o/geopulse/releases/tag/1.1.0

**Comment by FoxxMD** [comment]
Import seems to be working. Started at about 1.5 seconds between log messages doing 500 points/sec. After about 20 minutes slowed down to 13-16 seconds between log messages, down to 30 points/sec. Postgres cpu usage is high but that seems expected. Still importing, currently...

**Comment by tess1o** [comment]
What about CPU usage on backend (geopulse-backend)? I'm working on version `1.1.1` which improves logging messages and shows the correct progress in UI. 30 points/sec is too slow. It might be issue with HDD as well.

On my laptop I usually see 750-1500 rows/sec without degradation.

**Comment by FoxxMD** [comment]
This is all running on NVMe storage. backend cpu usage is minimal, less than 1%. postgres is actually around 10%, according to btop. It's just a high % of all running processes, but not total cpu capacity available.

EDIT: Up to 20 seconds per log line, ~25 points/s. Sometimes it bounces back up to 40-80. Kind of all over the place:

```
geopulse-backend  | 2025-10-27 14:40:25,005 INFO  [org.git.tes.geo.str.ser.StreamingTimelineGenerationService] (pool-8-thread-1) Successfully completed timeline regeneration for user 91da95af-3517-46c1-a711-5a11a1ebcf92 from timestamp 2025-10-27T14:40:24.999670922Z in 0.006 seconds
geopulse-backend  | 2025-10-27 14:40:33,246 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 498 new points. Duration: 20612ms, Throughput: 24.257713953037065 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:40:56,969 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 500 new points. Duration: 23722ms, Throughput: 21.077480819492454 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:41:08,167 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 491 new points. Duration: 11196ms, Throughput: 44.65880671668453 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:41:32,100 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 500 new points. Duration: 23931ms, Throughput: 20.893401863691444 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:41:54,605 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 497 new points. Duration: 22504ms, Throughput: 22.218272307145398 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:42:17,913 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 498 new points. Duration: 23305ms, Throughput: 21.454623471358076 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:42:37,640 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 495 new points. Duration: 19726ms, Throughput: 25.347257426746427 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:42:49,022 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 493 new points. Duration: 11379ms, Throughput: 43.94059231918446 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:43:11,701 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 497 new points. Duration: 22668ms, Throughput: 22.057526027880712 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:43:33,694 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 496 new points. Duration: 21992ms, Throughput: 22.735540196435068 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:43:35,698 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 494 new points. Duration: 2001ms, Throughput: 249.8750624687656 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:43:36,101 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 489 new points. Duration: 402ms, Throughput: 1243.7810945273632 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:43:36,543 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 491 new points. Duration: 441ms, Throughput: 1133.7868480725624 points/sec, Batch size: 250
geopulse-backend  | 2025-10-27 14:43:54,949 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-444) MERGE MODE: Processed 500 GPS points, imported 496 new points. Duration: 18404ms, Throughput: 27.16800695500978 points/sec, Batch size: 250

```

**Comment by tess1o** [comment]
Ok, I have some ideas how to improve performance, will deliver fix in next release.

**Comment by FoxxMD** [comment]
Hopefully my timeline is imported before then 😂 I think it's safe to close this. It's still importing but it _is_ importing so this issue is technically solved.

**Comment by FoxxMD** [comment]
Hey I realize this isn't fixed yet but wanted to update that 1.1.2 has the same behavior and now I have percent/point data as well. Import has been running for 2 hours and this is the current log line:

```
geopulse-backend  | 2025-10-29 15:43:25,886 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-78) MERGE MODE: Processed 500 points, imported 0 new, skipped 500 duplicates in 29763ms (16.799381782750395 points/sec) [607000 / 1232262 points, 49.3%]
geopulse-backend  | 2025-10-29 15:43:34,624 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-78) MERGE MODE: Processed 500 points, imported 0 new, skipped 500 duplicates in 8736ms (57.234432234432234 points/sec) [607500 / 1232262 points, 49.3%]
geopulse-backend  | 2025-10-29 15:44:17,277 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-78) MERGE MODE: Processed 500 points, imported 0 new, skipped 500 duplicates in 42652ms (11.722779705523774 points/sec) [608000 / 1232262 points, 49.3%]
geopulse-backend  | 2025-10-29 15:45:01,056 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-78) MERGE MODE: Processed 500 points, imported 0 new, skipped 500 duplicates in 43779ms (11.421000936522077 points/sec) [608500 / 1232262 points, 49.4%]
geopulse-backend  | 2025-10-29 15:45:29,221 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-78) MERGE MODE: Processed 500 points, imported 0 new, skipped 500 duplicates in 28164ms (17.753160062491123 points/sec) [609000 / 1232262 points, 49.4%]
geopulse-backend  | 2025-10-29 15:46:00,642 INFO  [org.git.tes.geo.imp.ser.BatchProcessor] (quarkus-virtual-thread-78) MERGE MODE: Processed 500 points, imported 0 new, skipped 500 duplicates in 31420ms (15.913430935709739 points/sec) [609500 / 1232262 points, 49.5%]
```

I tried to use "import only date range" and exclude the previously imported range. So far no points have been imported (all skipped). I think I made it about this far last time I tried to import (on 1.1.0), before restarting backend since it had slowed to a crawl and I didn't know how much progress had been made.

**Comment by tess1o** [comment]
It's very slow. How many points do you think you have in total? Here it tries to merge gps points during insertion and it's pretty slow as you can see. Maybe better option would be to wipe data from gps_points table and start import again with "Replace existing data in time range". In this case it will delete all points from min to max timestamp from your file and do quick import without duplication check.

**Comment by FoxxMD** [comment]
Using clear mode fixed the issue! BatchProcessor finished in ~5 minutes. Thanks for sticking with me through this issue.
