### ISSUE TITLE
Google Maps geocoder rendering places as numbers

### ISSUE THREAD

**Issue by FoxxMD** [tess1o/geopulse#63]
Google Maps as a geocoder (fallback) seems to work _ok_. In some instances it is getting the correct city and the Display Name is at least an address, though I wish it would be an actual place name.

However, for Places in Japan, the majority of successful(?) Places returned and rendered as numbers:

<img width="1576" height="1097" alt="Image" src="https://github.com/user-attachments/assets/f1ee0873-8450-4d55-b29f-b1282b361329" />

When regenerating timeline...

Some of the gmaps geocode attempts did fail

```
geopulse-backend  | 2025-10-27 12:34:28,082 ERROR [org.git.tes.geo.geo.ser.GeocodingServiceImpl] (executor-thread-2) Error getting address from coordinates: lon=-64.6354745, lat=18.39741675: org.eclipse.microprofile.faulttolerance.exceptions.CircuitBreakerOpenException: org.github.tess1o.geopulse.geocoding.service.GoogleMapsGeocodingService#reverseGeocode circuit breaker is open
geopulse-backend  | 	at io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker.inOpen(CircuitBreaker.java:120)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker.apply(CircuitBreaker.java:70)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.retry.Retry.retryLoopIteration(Retry.java:138)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.retry.Retry.lambda$retryLoop$0(Retry.java:86)
geopulse-backend  | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.timer.ThreadTimer$Task.run(ThreadTimer.java:194)
geopulse-backend  | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
geopulse-backend  | 	at io.smallrye.faulttolerance.vertx.VertxExecutor.lambda$execute$0(VertxExecutor.java:23)
geopulse-backend  | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
geopulse-backend  | 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
geopulse-backend  | 	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
geopulse-backend  | 	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
geopulse-backend  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:650)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
geopulse-backend  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
geopulse-backend  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
geopulse-backend  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
geopulse-backend  | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend  | 	at java.base@25/java.lang.Thread.run(Thread.java:1474)
geopulse-backend  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
geopulse-backend  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
geopulse-backend  | 
```

But it looks like these number Places were from successful queries:

```
geopulse-backend  | 2025-10-27 12:33:22,903 INFO  [org.git.tes.geo.geo.ser.GeocodingServiceImpl] (executor-thread-2) No cached location found, fetching from external service: lon=135.5056558, lat=34.6893136
geopulse-backend  | 2025-10-27 12:33:24,378 WARN  [org.git.tes.geo.geo.ser.GeocodingProviderFactory] (executor-thread-3) Primary provider 'photon' failed, trying fallback provider 'googlemaps': org.eclipse.microprofile.faulttolerance.exceptions.CircuitBreakerOpenException: org.github.tess1o.geopulse.geocoding.service.PhotonGeocodingService#reverseGeocode circuit breaker is open
geopulse-backend  | 	at io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker.inOpen(CircuitBreaker.java:120)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker.apply(CircuitBreaker.java:70)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.retry.Retry.retryLoopIteration(Retry.java:138)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.retry.Retry.lambda$retryLoop$0(Retry.java:86)
geopulse-backend  | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.timer.ThreadTimer$Task.run(ThreadTimer.java:194)
geopulse-backend  | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
geopulse-backend  | 	at io.smallrye.faulttolerance.vertx.VertxExecutor.lambda$execute$0(VertxExecutor.java:23)
geopulse-backend  | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
geopulse-backend  | 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
geopulse-backend  | 	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
geopulse-backend  | 	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
geopulse-backend  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:650)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
geopulse-backend  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
geopulse-backend  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
geopulse-backend  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
geopulse-backend  | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend  | 	at java.base@25/java.lang.Thread.run(Thread.java:1474)
geopulse-backend  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
geopulse-backend  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
geopulse-backend  | 
geopulse-backend  | 2025-10-27 12:33:24,517 INFO  [org.git.tes.geo.geo.ser.GeocodingServiceImpl] (executor-thread-2) Successfully fetched address from GoogleMaps: lon=135.5056558, lat=34.6893136, displayName=日宝北浜ビル
geopulse-backend  | 2025-10-27 12:33:26,526 INFO  [org.git.tes.geo.geo.ser.GeocodingServiceImpl] (executor-thread-2) No cached location found, fetching from external service: lon=135.50136525, lat=34.73410575
geopulse-backend  | 2025-10-27 12:33:28,136 WARN  [org.git.tes.geo.geo.ser.GeocodingProviderFactory] (executor-thread-6) Primary provider 'photon' failed, trying fallback provider 'googlemaps': org.eclipse.microprofile.faulttolerance.exceptions.CircuitBreakerOpenException: org.github.tess1o.geopulse.geocoding.service.PhotonGeocodingService#reverseGeocode circuit breaker is open
geopulse-backend  | 	at io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker.inOpen(CircuitBreaker.java:120)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.circuit.breaker.CircuitBreaker.apply(CircuitBreaker.java:70)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.retry.Retry.retryLoopIteration(Retry.java:138)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.retry.Retry.lambda$retryLoop$0(Retry.java:86)
geopulse-backend  | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
geopulse-backend  | 	at io.smallrye.faulttolerance.core.timer.ThreadTimer$Task.run(ThreadTimer.java:194)
geopulse-backend  | 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
geopulse-backend  | 	at io.smallrye.faulttolerance.vertx.VertxExecutor.lambda$execute$0(VertxExecutor.java:23)
geopulse-backend  | 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
geopulse-backend  | 	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
geopulse-backend  | 	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
geopulse-backend  | 	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
geopulse-backend  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:650)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
geopulse-backend  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
geopulse-backend  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
geopulse-backend  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
geopulse-backend  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
geopulse-backend  | 	at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
geopulse-backend  | 	at java.base@25/java.lang.Thread.run(Thread.java:1474)
geopulse-backend  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
geopulse-backend  | 	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
geopulse-backend  | 
geopulse-backend  | 2025-10-27 12:33:28,290 INFO  [org.git.tes.geo.geo.ser.GeocodingServiceImpl] (executor-thread-2) Successfully fetched address from GoogleMaps: lon=135.50136525, lat=34.73410575, displayName=1
```

**Comment by tess1o** [comment]
I will check what info is returned for Japanese addresses.  GeoPulse tries to use available information to build a good user-friendly address but it appears the common rule is not applicable for Japan.

You can try to use Photon or Nomatim as workaround for these addresses, not sure if they perform better.

**Comment by minhhieu219** [comment]
Same here. Japanese address is in xx丁目xx番地xx号 format, can be written as xx-xx-xx. That's why it only returns number.

**Comment by FoxxMD** [comment]
Does gmaps return Romaji?

EDIT: Kind of. Here's a reverse geocoding for a shop in Japan:

<img width="981" height="659" alt="Image" src="https://github.com/user-attachments/assets/0b13b834-0ac1-4cca-92f4-bc9dd048bd80" />

https://maps.googleapis.com/maps/api/geocode/json?key=YOUR_KEY&latlng=36.328592,139.820516

```json
{
   "plus_code" : 
   {
      "compound_code" : "8RHC+C6J Oyama, Tochigi, Japan",
      "global_code" : "8Q8X8RHC+C6J"
   },
   "results" : 
   [
      {
         "address_components" : 
         [
            {
               "long_name" : "9",
               "short_name" : "9",
               "types" : 
               [
                  "premise"
               ]
            },
            {
               "long_name" : "２",
               "short_name" : "２",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_4"
               ]
            },
            {
               "long_name" : "3-chōme",
               "short_name" : "3-chōme",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_3"
               ]
            },
            {
               "long_name" : "Jōhoku",
               "short_name" : "Jōhoku",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_2"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            },
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            }
         ],
         "formatted_address" : "Japan, 〒323-0029 Tochigi, Oyama, Jōhoku, 3-chōme−２−９",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3286834,
                  "lng" : 139.8206293
               },
               "southwest" : 
               {
                  "lat" : 36.32840729999999,
                  "lng" : 139.8203901
               }
            },
            "location" : 
            {
               "lat" : 36.3285485,
               "lng" : 139.8205096
            },
            "location_type" : "ROOFTOP",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.32989433029149,
                  "lng" : 139.8218586802915
               },
               "southwest" : 
               {
                  "lat" : 36.3271963697085,
                  "lng" : 139.8191607197085
               }
            }
         },
         "navigation_points" : 
         [
            {
               "location" : 
               {
                  "latitude" : 36.3286061,
                  "longitude" : 139.8203639
               }
            }
         ],
         "place_id" : "ChIJy_fdE1NOH2ARK0qpqh2AfJc",
         "types" : 
         [
            "premise",
            "street_address"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "2",
               "short_name" : "2",
               "types" : 
               [
                  "premise"
               ]
            },
            {
               "long_name" : "3-chōme",
               "short_name" : "3-chōme",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_3"
               ]
            },
            {
               "long_name" : "Jōhoku",
               "short_name" : "Jōhoku",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_2"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            },
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            }
         ],
         "formatted_address" : "3-chōme-2 Jōhoku, Oyama, Tochigi 323-0029, Japan",
         "geometry" : 
         {
            "location" : 
            {
               "lat" : 36.3285275,
               "lng" : 139.8204541
            },
            "location_type" : "ROOFTOP",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3298764802915,
                  "lng" : 139.8218030802915
               },
               "southwest" : 
               {
                  "lat" : 36.3271785197085,
                  "lng" : 139.8191051197085
               }
            }
         },
         "navigation_points" : 
         [
            {
               "location" : 
               {
                  "latitude" : 36.3285732,
                  "longitude" : 139.8203412
               }
            }
         ],
         "place_id" : "ChIJhUez7AJPH2ARfIvW8HUMHW0",
         "plus_code" : 
         {
            "compound_code" : "8RHC+C5 Oyama, Tochigi, Japan",
            "global_code" : "8Q8X8RHC+C5"
         },
         "types" : 
         [
            "establishment",
            "point_of_interest",
            "storage"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "10",
               "short_name" : "10",
               "types" : 
               [
                  "premise"
               ]
            },
            {
               "long_name" : "２",
               "short_name" : "２",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_4"
               ]
            },
            {
               "long_name" : "3-chōme",
               "short_name" : "3-chōme",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_3"
               ]
            },
            {
               "long_name" : "Jōhoku",
               "short_name" : "Jōhoku",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_2"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            },
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            }
         ],
         "formatted_address" : "Japan, 〒323-0029 Tochigi, Oyama, Jōhoku, 3-chōme−２−１０",
         "geometry" : 
         {
            "location" : 
            {
               "lat" : 36.328477,
               "lng" : 139.8206234
            },
            "location_type" : "ROOFTOP",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3298259802915,
                  "lng" : 139.8219723802915
               },
               "southwest" : 
               {
                  "lat" : 36.3271280197085,
                  "lng" : 139.8192744197085
               }
            }
         },
         "navigation_points" : 
         [
            {
               "location" : 
               {
                  "latitude" : 36.3286524,
                  "longitude" : 139.8207369
               }
            }
         ],
         "place_id" : "ChIJd_y3EVNOH2ARWVQk_KAUOAI",
         "plus_code" : 
         {
            "compound_code" : "8RHC+96 Oyama, Tochigi, Japan",
            "global_code" : "8Q8X8RHC+96"
         },
         "types" : 
         [
            "street_address"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "8RHC+C6",
               "short_name" : "8RHC+C6",
               "types" : 
               [
                  "plus_code"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            }
         ],
         "formatted_address" : "8RHC+C6 Oyama, Tochigi, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.328625,
                  "lng" : 139.820625
               },
               "southwest" : 
               {
                  "lat" : 36.3285,
                  "lng" : 139.8205
               }
            },
            "location" : 
            {
               "lat" : 36.328592,
               "lng" : 139.820516
            },
            "location_type" : "GEOMETRIC_CENTER",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.32991148029149,
                  "lng" : 139.8219114802915
               },
               "southwest" : 
               {
                  "lat" : 36.32721351970849,
                  "lng" : 139.8192135197085
               }
            }
         },
         "place_id" : "GhIJFt16TQ8qQkARCDvFqkF6YUA",
         "plus_code" : 
         {
            "compound_code" : "8RHC+C6 Oyama, Tochigi, Japan",
            "global_code" : "8Q8X8RHC+C6"
         },
         "types" : 
         [
            "plus_code"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "Tochigi Prefectural Route 339",
               "short_name" : "Tochigi Prefectural Route 339",
               "types" : 
               [
                  "route"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            },
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            }
         ],
         "formatted_address" : "Tochigi Prefectural Rte 339, Oyama, Tochigi 323-0029, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3288445,
                  "lng" : 139.8204226
               },
               "southwest" : 
               {
                  "lat" : 36.3283532,
                  "lng" : 139.8201168
               }
            },
            "location" : 
            {
               "lat" : 36.3285989,
               "lng" : 139.8202697
            },
            "location_type" : "GEOMETRIC_CENTER",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.32994783029149,
                  "lng" : 139.8216186802915
               },
               "southwest" : 
               {
                  "lat" : 36.3272498697085,
                  "lng" : 139.8189207197085
               }
            }
         },
         "place_id" : "ChIJhb29FFNOH2ARWsp53oOm-mM",
         "types" : 
         [
            "route"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "3 Chome",
               "short_name" : "3 Chome",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_3"
               ]
            },
            {
               "long_name" : "Johoku",
               "short_name" : "Johoku",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_2"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            },
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            }
         ],
         "formatted_address" : "3 Chome Johoku, Oyama, Tochigi 323-0029, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3288272,
                  "lng" : 139.8256556
               },
               "southwest" : 
               {
                  "lat" : 36.3244353,
                  "lng" : 139.8189183
               }
            },
            "location" : 
            {
               "lat" : 36.3267206,
               "lng" : 139.8221007
            },
            "location_type" : "APPROXIMATE",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3288272,
                  "lng" : 139.8256556
               },
               "southwest" : 
               {
                  "lat" : 36.3244353,
                  "lng" : 139.8189183
               }
            }
         },
         "place_id" : "ChIJ7UpUJFJOH2ARz8UrMNz0dmY",
         "types" : 
         [
            "political",
            "sublocality",
            "sublocality_level_3"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "Johoku",
               "short_name" : "Johoku",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_2"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            },
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            }
         ],
         "formatted_address" : "Johoku, Oyama, Tochigi 323-0029, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3303417,
                  "lng" : 139.8256556
               },
               "southwest" : 
               {
                  "lat" : 36.31593600000001,
                  "lng" : 139.8114634
               }
            },
            "location" : 
            {
               "lat" : 36.3236135,
               "lng" : 139.8214611
            },
            "location_type" : "APPROXIMATE",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3303417,
                  "lng" : 139.8256556
               },
               "southwest" : 
               {
                  "lat" : 36.31593600000001,
                  "lng" : 139.8114634
               }
            }
         },
         "place_id" : "ChIJL61mzlZOH2ARwCipoIJoy0U",
         "types" : 
         [
            "political",
            "sublocality",
            "sublocality_level_2"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "323-0029",
               "short_name" : "323-0029",
               "types" : 
               [
                  "postal_code"
               ]
            },
            {
               "long_name" : "Johoku",
               "short_name" : "Johoku",
               "types" : 
               [
                  "political",
                  "sublocality",
                  "sublocality_level_2"
               ]
            },
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            }
         ],
         "formatted_address" : "323-0029, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3303417,
                  "lng" : 139.8256556
               },
               "southwest" : 
               {
                  "lat" : 36.31593600000001,
                  "lng" : 139.8114634
               }
            },
            "location" : 
            {
               "lat" : 36.3236135,
               "lng" : 139.8214611
            },
            "location_type" : "APPROXIMATE",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.3303417,
                  "lng" : 139.8256556
               },
               "southwest" : 
               {
                  "lat" : 36.31593600000001,
                  "lng" : 139.8114634
               }
            }
         },
         "place_id" : "ChIJQ2qxAFFOH2ARswyx5p_pKDs",
         "types" : 
         [
            "postal_code"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "Oyama",
               "short_name" : "Oyama",
               "types" : 
               [
                  "locality",
                  "political"
               ]
            },
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            }
         ],
         "formatted_address" : "Oyama, Tochigi, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 36.38876339999999,
                  "lng" : 139.9150697
               },
               "southwest" : 
               {
                  "lat" : 36.2233912,
                  "lng" : 139.6872448
               }
            },
            "location" : 
            {
               "lat" : 36.3146653,
               "lng" : 139.8001493
            },
            "location_type" : "APPROXIMATE",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 36.38876339999999,
                  "lng" : 139.9150697
               },
               "southwest" : 
               {
                  "lat" : 36.2233912,
                  "lng" : 139.6872448
               }
            }
         },
         "place_id" : "ChIJnT_mBO1OH2ARnoVkxjDxn4o",
         "types" : 
         [
            "locality",
            "political"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "Tochigi",
               "short_name" : "Tochigi",
               "types" : 
               [
                  "administrative_area_level_1",
                  "political"
               ]
            },
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            }
         ],
         "formatted_address" : "Tochigi, Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 37.1550551,
                  "lng" : 140.2921256
               },
               "southwest" : 
               {
                  "lat" : 36.1997662,
                  "lng" : 139.3265759
               }
            },
            "location" : 
            {
               "lat" : 36.6714739,
               "lng" : 139.8547266
            },
            "location_type" : "APPROXIMATE",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 37.1550551,
                  "lng" : 140.2921256
               },
               "southwest" : 
               {
                  "lat" : 36.1997662,
                  "lng" : 139.3265759
               }
            }
         },
         "place_id" : "ChIJ7RWXa1VwH2ARB9AguZ5FZW0",
         "types" : 
         [
            "administrative_area_level_1",
            "political"
         ]
      },
      {
         "address_components" : 
         [
            {
               "long_name" : "Japan",
               "short_name" : "JP",
               "types" : 
               [
                  "country",
                  "political"
               ]
            }
         ],
         "formatted_address" : "Japan",
         "geometry" : 
         {
            "bounds" : 
            {
               "northeast" : 
               {
                  "lat" : 45.6412626,
                  "lng" : 154.0031455
               },
               "southwest" : 
               {
                  "lat" : 20.3585295,
                  "lng" : 122.8554688
               }
            },
            "location" : 
            {
               "lat" : 36.204824,
               "lng" : 138.252924
            },
            "location_type" : "APPROXIMATE",
            "viewport" : 
            {
               "northeast" : 
               {
                  "lat" : 45.6412626,
                  "lng" : 154.0031455
               },
               "southwest" : 
               {
                  "lat" : 20.3585295,
                  "lng" : 122.8554688
               }
            }
         },
         "place_id" : "ChIJLxl_1w9OZzQRRFJmfNR1QvU",
         "types" : 
         [
            "country",
            "political"
         ]
      }
   ],
   "status" : "OK"
}
```

The street name and city are at least in romaji. Wish it returned the actual Place name like the map shows.

**Comment by tess1o** [comment]
For Google Maps I tried to be "smart" (obviously it failed) and calculate display address for timeline as a combination of establishment name and street.

Establishment is calculated as `long_name` from types (either of them, what ever is available):

establishment
point_of_interest
premise

Street name is calculated as `long_name` of 

street_number
route


it appears this approach works bad for Japan. 

A simple and straightforward fix is to directly use `formatted_address` field from the response. I didn't like that approach because the name was too long and it includes country, region, zip address, which I didn't need on the timeline.

Happy to hear your ideas how to solve this.

**Comment by tess1o** [comment]
Google Maps and Mapbox (similar issue) is fixed and will be available in next release.

**Comment by tess1o** [comment]
The issue with Google Maps and Mapbox is fixed in 1.2.1. Full changelog: https://github.com/tess1o/geopulse/releases/tag/1.2.1

**Comment by FoxxMD** [comment]
It's better than it was! But not fully solved, yet. The display name is the full address but the Cities are still mostly numbers. Appreciate the improvements so far, though. Thanks!

<img width="1643" height="792" alt="Image" src="https://github.com/user-attachments/assets/80aca591-dc36-4bbd-a231-8143b403fa1e" />

**Comment by tess1o** [comment]
I didn't really pay attention to cities, was concerned about addresses only. Will check cities as well. thanks.

**Comment by tess1o** [comment]
Current logic:
```
    private String extractCity(List<GoogleMapsAddressComponent> components) {
        if (components == null) {
            return null;
        }

        return components.stream()
                .filter(c -> c.getTypes() != null &&
                        (c.getTypes().contains("locality") ||
                                c.getTypes().contains("administrative_area_level_2") ||
                                c.getTypes().contains("sublocality")))
                .map(GoogleMapsAddressComponent::getLongName)
                .findFirst()
                .orElse(null);
    }
```

But instead I should check the city value in this order:

```
        "locality",
        "postal_town",
        "administrative_area_level_3",
        "administrative_area_level_2",
        "administrative_area_level_1",
```

Find `address_components` with `type = locality`. If found - get `long_name`. If not found - find `postal_town` . If not found - check `administrative_area_level_3` and so on.

I will fix it today and probably tomorrow will deliver new release with fixes.

**Comment by tess1o** [comment]
Fixed in release `1.2.2`.  Full changelog is available here: https://github.com/tess1o/geopulse/releases/tag/1.2.2

**Comment by FoxxMD** [comment]
It worked! Thank you for the hard work ❤️
