### ISSUE TITLE
Search favorites by gps points fails on 65K+ points

### ISSUE THREAD

**Issue by tess1o** [tess1o/geopulse#70]
SELECT DISTINCT ON (ic.input_lon, ic.input_lat)
f.id, ic.input_lon, ic.input_lat
FROM favorite_locations f
CROSS JOIN input_coords ic
WHERE f.user_id = ?
AND (
(f.type = 'POINT'
AND ST_DWithin(f.geometry::geography, ic.input_point::geography, ?)
)
OR
(f.type = 'AREA'
AND (ST_Contains(f.geometry, ic.input_point)
OR ST_DWithin(ST_Boundary(f.geometry)::geography, ic.input_point::geography, ?)
)
)
)
ORDER BY ic.input_lon, ic.input_lat,
CASE WHEN f.type = 'AREA' AND ST_Contains(f.geometry, ic.input_point) THEN 1 ELSE 2 END,
ST_Distance(f.geometry::geography, ic.input_point::geography)
]
at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:84)
at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:34)
at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:115)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:198)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
at org.hibernate.sql.exec.internal.StandardStatementCreator.createStatement(StandardStatementCreator.java:47)
at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:271)
at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:200)
at org.hibernate.sql.results.jdbc.internal.AbstractResultSetAccess.getResultSetMetaData(AbstractResultSetAccess.java:53)
at org.hibernate.sql.results.jdbc.internal.AbstractResultSetAccess.getColumnCount(AbstractResultSetAccess.java:67)
at org.hibernate.query.results.internal.ResultSetMappingImpl.resolve(ResultSetMappingImpl.java:188)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.resolveJdbcValues(JdbcSelectExecutorStandardImpl.java:358)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.resolveJdbcValuesSource(JdbcSelectExecutorStandardImpl.java:332)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:135)
at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:100)
at org.hibernate.sql.exec.spi.JdbcSelectExecutor.executeQuery(JdbcSelectExecutor.java:64)
at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:138)
at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:115)
at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:105)
at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:138)
at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:763)
at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:154)
at org.hibernate.query.Query.getResultList(Query.java:121)
at org.github.tess1o.geopulse.favorites.repository.FavoritesRepository.findByPointsBatch(FavoritesRepository.java:164)
at org.github.tess1o.geopulse.favorites.repository.FavoritesRepository_ClientProxy.findByPointsBatch(Unknown Source)
at org.github.tess1o.geopulse.favorites.service.FavoriteLocationService.findByPointsBatch(FavoriteLocationService.java:163)
at org.github.tess1o.geopulse.favorites.service.FavoriteLocationService_ClientProxy.findByPointsBatch(Unknown Source)
at org.github.tess1o.geopulse.shared.service.LocationPointResolver.resolveLocationsWithReferencesBatch(LocationPointResolver.java:88)
at org.github.tess1o.geopulse.shared.service.LocationPointResolver_ClientProxy.resolveLocationsWithReferencesBatch(Unknown Source)
at org.github.tess1o.geopulse.streaming.engine.TimelineEventFinalizationService.populateStayLocations(TimelineEventFinalizationService.java:110)
at org.github.tess1o.geopulse.streaming.engine.TimelineEventFinalizationService_ClientProxy.populateStayLocations(Unknown Source)
at org.github.tess1o.geopulse.streaming.engine.StreamingTimelineProcessor.processPoints(StreamingTimelineProcessor.java:85)
at org.github.tess1o.geopulse.streaming.engine.StreamingTimelineProcessor_ClientProxy.processPoints(Unknown Source)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService.generateTimelineFromTimestamp(StreamingTimelineGenerationService.java:110)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_Subclass.generateTimelineFromTimestamp$$superforward(Unknown Source)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_Subclass$$function$$2.apply(Unknown Source)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:335)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_Subclass.generateTimelineFromTimestamp(Unknown Source)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService.regenerateFullTimeline(StreamingTimelineGenerationService.java:146)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_Subclass.regenerateFullTimeline$$superforward(Unknown Source)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_Subclass$$function$$1.apply(Unknown Source)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_Subclass.regenerateFullTimeline(Unknown Source)
at org.github.tess1o.geopulse.streaming.service.StreamingTimelineGenerationService_ClientProxy.regenerateFullTimeline(Unknown Source)
at org.github.tess1o.geopulse.streaming.rest.StreamingTimelineResource.regenerateAllTimeline(StreamingTimelineResource.java:124)
at org.github.tess1o.geopulse.streaming.rest.StreamingTimelineResource_Subclass.regenerateAllTimeline$$superforward(Unknown Source)
at org.github.tess1o.geopulse.streaming.rest.StreamingTimelineResource_Subclass$$function$$3.apply(Unknown Source)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:27)
at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor.intercept(StandardSecurityCheckInterceptor.java:44)
at io.quarkus.resteasy.reactive.server.runtime.StandardSecurityCheckInterceptor_RolesAllowedInterceptor_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
at org.github.tess1o.geopulse.streaming.rest.StreamingTimelineResource_Subclass.regenerateAllTimeline(Unknown Source)
at org.github.tess1o.geopulse.streaming.rest.StreamingTimelineResource_ClientProxy.regenerateAllTimeline(Unknown Source)
at org.github.tess1o.geopulse.streaming.rest.StreamingTimelineResource$quarkusrestinvoker$regenerateAllTimeline_bfc76f9c84a52e04aba99d8264ad9af99f1459b6.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:183)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:645)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base@25/java.lang.Thread.runWith(Thread.java:1487)
at java.base@25/java.lang.Thread.run(Thread.java:1474)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:808)
Caused by: org.postgresql.util.PSQLException: PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 73,347 parameters
at org.postgresql.jdbc.PgPreparedStatement.(PgPreparedStatement.java:107)
at org.postgresql.jdbc.PgPreparedStatement.(PgPreparedStatement.java:93)
at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1426)
at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1878)
at io.agroal.pool.wrapper.ConnectionWrapper.prepareStatement(ConnectionWrapper.java:661)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$4.doPrepare(StatementPreparerImpl.java:158)
at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:187)
... 93 more

**Comment by tess1o** [comment]
Fixed in Release `1.1.1`. Full changelog: https://github.com/tess1o/geopulse/releases/tag/1.1.1

**Comment by nksoori** [comment]
This error still comes up for me when I try to regenerate the timeline. 

Caused by: org.postgresql.util.PSQLException: PreparedStatement can have at most 65,535 parameters. Please consider using arrays, or splitting the query in several ones, or using COPY. Given query has 73,346 parameters

**Comment by tess1o** [comment]
Can you please provide full error message? Whole stacktrace? Thanks

**Comment by nksoori** [comment]
[gepulse-backend.log](https://github.com/user-attachments/files/23195061/gepulse-backend.log)

I've attached a log output here

**Comment by tess1o** [comment]
So actually the stracktrace is different - it fails in different place but with similar root cause. I missed that during my initial fix. Will also fix this one in next release

**Comment by tess1o** [comment]
Hello,

it's fixed in version `1.1.2`. Full release notes are here: https://github.com/tess1o/geopulse/releases/tag/1.1.2

**Comment by nksoori** [comment]
It finally imported everything. There were some errors popping up on the logs. But the data was corrected. One issue was that the backend was not accessible when the last data was being mapped. It took a lot of time as well (Maybe an hour or a bit more). 

A suggestion would be to show the status/what the backend is doing on the UI while "Regenerate Timeline" is working. 

Amazing work! Thanks

**Comment by tess1o** [comment]
Yeah, that's the first import is slow. Now on a daily basis it should be really fast with small resource consumption.

"Regenerate Timeline" - it's loading reverse geocoding data for 95% of time. Timeline generation itself is pretty fast even on big volumes (1.5 million records - about 1 minute when reverse geocoding is already in DB).

 I will check if this can be further improved to show how many geocoding points we still need to reconcile.

I believe this ticket can be closed for now.
