### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by drshajul** [tess1o/geopulse#9]
Error 400:

From HomeAssistant
```
content: ""
status: 400
headers:
  Server: nginx/1.28.0
  Date: Thu, 23 Oct 2025 10:39:52 GMT
  Content-Length: "0"
  Connection: keep-alive
  Content-Security-Policy: >-
    default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'
    https://cdnjs.cloudflare.com https://unpkg.com; style-src 'self'
    'unsafe-inline' https://cdnjs.cloudflare.com https://unpkg.com; font-src
    'self' https://cdnjs.cloudflare.com; img-src 'self' data: https: blob:;
    connect-src 'self' https:; frame-ancestors 'none'; base-uri 'self';
    form-action 'self'
  Permissions-Policy: camera=(), microphone=(), geolocation=(self), payment=()
  Referrer-Policy: strict-origin-when-cross-origin
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
```

**Comment by tess1o** [comment]
Can you provide more information? What did you do in GeoPulse app, what configurations dis you apply in HA? Where this log comes from?

**Comment by drshajul** [comment]
This log is from home assistant -> Developer tools -> Actions

The settings are same as given on the HomeAssistant page on GeoPulse. I changed iphone16 to my device name

**Comment by tess1o** [comment]
This is what I have in ./configuration.yaml in HA:

```
rest_command:
  send_gps_data:
    url: "https://geopulse.mydomain.com/api/homeassistant"
    method: POST
    headers:
      content-type: "application/json"
      Authorization: Bearer test
    payload: >
      {
        "device_id": "iphone_16",
        "timestamp": "{{ now().isoformat() }}",
        "location": {
          "latitude": {{ state_attr('device_tracker.iphone_16', 'latitude') }},
          "longitude": {{ state_attr('device_tracker.iphone_16', 'longitude') }},
          "accuracy": {{ state_attr('device_tracker.iphone_16', 'gps_accuracy') | default(0) }},
          "altitude": {{ state_attr('device_tracker.iphone_16', 'altitude') | default(0) }},
          "speed": {{ state_attr('device_tracker.iphone_16', 'speed') | default(0, true) }}
        },
        "battery": {
          "level": {{ state_attr('device_tracker.iphone_16', 'battery_level') | default(0) }}
        }
      }
```

400 error looks like GeoPulse receives incorrect JSON payload from HA. I suspect some of those parameters are not available and thus incorrect json is sent (however I provided default values for all non-critical fields, except latitude/longtitude which are mandatory.

Can you check what information do you have in `home-assistant.log`  (in the same folder as `configuration.yaml`) ? 
Please also check logs from geopulse-backend if you see any errors.

If nothing works I'll provide an updated backend with more detailed logging to see the actual request body (currently not printed for security and performance reasons).

Thanks.

**Comment by FoxxMD** [comment]
For my android device I had to modify battery level. There was no battery_level attribute on the device_tracker but there was a sensor for my device.

```
"level": {{ states('sensor.pixel_9a_battery_level') | default(0) }}
```

**Comment by tess1o** [comment]
Most likely that's the reason. On iPhone the structure is different. I will update instructions with proper value to support both iphone and android

**Comment by tess1o** [comment]
This issue is fixed in release 1.0.3. In your `.env` file set `GEOPULSE_VERSION=1.0.3` and redeploy the frontend and backend.

**Comment by c1llin** [comment]
> This issue is fixed in release 1.0.3. In your `.env` file set `GEOPULSE_VERSION=1.0.3` and redeploy the frontend and backend.

I'm still experiencing this.

```
send_gps_data:
    url: "https://geopulse.domain.com/api/homeassistant"
    method: POST
    headers:
      content-type: "application/json"
      Authorization: Bearer 123456789
    payload: >
      {
        "device_id": "S24_Ultra",
        "timestamp": "{{ now().isoformat() }}",
        "location": {
          "latitude": {{ state_attr('device_tracker.phone', 'latitude') }},
          "longitude": {{ state_attr('device_tracker.phone', 'longitude') }},
          "accuracy": {{ state_attr('device_tracker.phone', 'gps_accuracy') | default(0) }},
          "altitude": {{ state_attr('device_tracker.phone', 'altitude') | default(0) }},
          "speed": {{ state_attr('device_tracker.phone', 'speed') | default(0) }}
        },
        "battery": {
          "level": {{ state_attr('device_tracker.phone', 'battery_level') | default(0) }}
        }
      }
```

Docker log:

`"POST /api/homeassistant HTTP/1.1" 400 0 "-" "HomeAssistant/2025.10.4 aiohttp/3.12.15 Python/3.13"`

Home Assistant log:

`Error. Url: https://geopulse.domain.com/api/homeassistant. Status code 400. Payload: b'{\n "device_id": "S24_Ultra",\n "timestamp": "2025-10-30T16:22:30.323284+01:00",\n "location": {\n "latitude": 12.3456789,\n "longitude": 1.23456789,\n "accuracy": 100,\n "altitude": None,\n "speed": None\n },\n "battery": {\n "level": 63\n }\n}'`

**Comment by tess1o** [comment]
`"altitude": None `
this is the issue. However, according to the config it should return 0, not None.

Try this:

`"altitude": {{ state_attr('device_tracker.phone', 'altitude') | default(0, true) }},`

Probably in your case Altitude property exists but it's None and `default(0)` doesn't replace it because technically some value is present.

**Comment by c1llin** [comment]
> `"altitude": None ` this is the issue. However, according to the config it should return 0, not None.
> 
> Try this:
> 
> `"altitude": {{ state_attr('device_tracker.phone', 'altitude') | default(0, true) }},`
> 
> Probably in your case Altitude property exists but it's None and `default(0)` doesn't replace it because technically some value is present.

Yeah that fixed it!
I also did the same for speed btw.

**Comment by tess1o** [comment]
Good to know, I will update instructions

**Comment by tess1o** [comment]
I have updated instruction, UI changes will be available in release `1.1.4`

**Comment by Vinod1452** [comment]
`WARNING (MainThread) [homeassistant.components.rest_command] Error. Url: http://192.168.29.186:5555/api/homeassistant. Status code 400. Payload: b'{\n "device_id": "vinod_iphone",\n "timestamp": "2026-01-19T22:41:30.830997+05:30",\n "location": {\n "latitude": 18.318489832826206,\n "longitude": 77.66308536577694,\n "accuracy": 24,\n "altitude": 743.9295972558263,\n "speed": 0\n },\n "battery": {\n "level": 65\n }'`

Whats wrong in this? getting erron home-assistant log. nothing in geopulse backend logs, device id is wrong? 

```rest_command:
  send_gps_data:
    url: "http://192.168.29.166:5555/api/homeassistant"
    method: POST
    headers:
      content-type: "application/json"
      Authorization: asertwertyhbnwfaef4d5555
    payload: >
      {
        "device_id": "vinod_iphone",
        "timestamp": "{{ now().isoformat() }}",
        "location": {
          "latitude": {{ state_attr('device_tracker.iphone', 'latitude') }},
          "longitude": {{ state_attr('device_tracker.iphone', 'longitude') }},
          "accuracy": {{ state_attr('device_tracker.iphone', 'gps_accuracy') | default(0, true) }},
          "altitude": {{ state_attr('device_tracker.iphone', 'altitude') | default(0, true) }},
          "speed": {{ state_attr('device_tracker.iphone', 'speed') | default(0, true) }}
        },
        "battery": {
          "level": {{ state_attr('device_tracker.iphone', 'battery_level') | default(states('sensor.iphone_battery_level'), true) | d>
        }```

**Comment by tess1o** [comment]
Hello,

I can see 2 problems:

```
Authorization: asertwertyhbnwfaef4d5555
```
It should be :

```
Authorization: Bearer asertwertyhbnwfaef4d5555
```

At the very end of payload you do not close "}", so the JSON is not valid. Correct command:

```
  rest_command:                                                                                                                                                                                                        
    send_gps_data:                                                                                                                                                                                                     
      url: "http://192.168.29.166:5555/api/homeassistant"                                                                                                                                                              
      method: POST                                                                                                                                                                                                     
      headers:                                                                                                                                                                                                         
        content-type: "application/json"                                                                                                                                                                               
        Authorization: Bearer asertwertyhbnwfaef4d5555                                                                                                                                                                 
      payload: >                                                                                                                                                                                                       
        {                                                                                                                                                                                                              
          "device_id": "vinod_iphone",                                                                                                                                                                                 
          "timestamp": "{{ now().isoformat() }}",                                                                                                                                                                      
          "location": {                                                                                                                                                                                                
            "latitude": {{ state_attr('device_tracker.iphone', 'latitude') }},                                                                                                                                         
            "longitude": {{ state_attr('device_tracker.iphone', 'longitude') }},                                                                                                                                       
            "accuracy": {{ state_attr('device_tracker.iphone', 'gps_accuracy') | default(0, true) }},                                                                                                                  
            "altitude": {{ state_attr('device_tracker.iphone', 'altitude') | default(0, true) }},                                                                                                                      
            "speed": {{ state_attr('device_tracker.iphone', 'speed') | default(0, true) }}                                                                                                                             
          },                                                                                                                                                                                                           
          "battery": {                                                                                                                                                                                                 
            "level": {{ state_attr('device_tracker.iphone', 'battery_level') | default(states('sensor.iphone_battery_level'), true) | default(0, true) }}                                                              
          }                                                                                                                                                                                                            
        }                                                                                                                                                                                                              
 ```
